module.exports = ["@ilMircu ar fi mersi de minune. Dar se serveau in locatii diferite :))",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Blogsale: RO:         Primul meu blogsale, cu lucruri pe care vreau sa le dau, pentru  a face loc altora. Pret... ",
                  "Toţi românii de pe tumblr să dea reblog. ",
                  "Peste 80 de persoane aflate într-o ambarcaţiune în derivă, salvate de poliţiştii de frontieră https://t.co/4P5NZAtuun",
                  "Am apreciat un videoclip pe @YouTube de la @playgamepro,  [SA:MP] W/ KTUD0R | Trupa DILIE",
                  "Tocmai am cumpărat Denim Street Shirt, White Fall Sweater pe Stardoll. Aruncă o privire în Suite-ul meu! ",
                  "@RocioBelen001 PE LI CU LON ♥",
                  "Am apreciat un videoclip pe @YouTube,  Simulator - City Bus Simulator München  - Citybus Simulator München",
                  "ALEGERI PREZIDENȚIALE 2014. Elena Udrea: „Îl dau jos pe Victor Ponta într-o săptămână”  ",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Cum arata un BIOS si setarile BIOS-ului",
                  "Viata ar putea fi minunata daca oamenii te-ar lasa in pace !  Charlie Chaplin ",
                  " Salut pe toti cei pe  care... ",
                  "...în câteva săptămâni am să urc pe youtube un proiect de Spoken Poetry semnat Elena Netcu!",
                  "Poezie și Trăiri ",
                  "O MAI ŢII MINTE PE BULGĂROAICA LUI COSTI? ANDREA A SLĂBIT ŞI ARATĂ ŞI MAI BINE DECÂT ŞTIAI!... ",
                  " MC-Risk  Financial  Regulatory Compliance, PE&amp;CE; Consultant + in   ",
                  " alimente pe care NU ai voie să le ratezi la micul dejun ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup ",
                  "Viața le 'mparte mereu așa, totul se 'ntoarce asupra ta. Poți fugi dar nu te poți ascunde, soarta te găsește oriunde ;)",
                  "@nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se bazeaza pe capital.",
                  "@nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se bazeaza pe capital.",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Gabriel Cotabiţă - Pagină oficială a fost pe la Discotecă într-o... ",
                  "Un primar vrea interzicerea reclamelor verzi la farmacii: Ii agreseaza vizual pe soferi ",
                  "Urgie pe Himalaya: Cel putin 17 alpinisti si serpasi au murit din cauza vremii ",
                  "Cât ne costă o sinecură la UNESCO: 62.400 euro pe an | Romania Libera ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Am apreciat un videoclip pe @YouTube,  citeva explicatii despre setarile din bios",
                  "@alinaconst Da. E doar o bucurie trista pe care o traiesc. Viata merge mai inainte. Asa am fost educat. Am predat si mi-am predat o lectie.",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Substance Painter 1 - Getting Started 01 - UI",
                  "O MAI ŢII MINTE PE BULGĂROAICA LUI COSTI? ANDREA A SLĂBIT ŞI ARATĂ ŞI MAI BINE DECÂT ŞTIAI!... ",
                  "O MAI ŢII MINTE PE BULGĂROAICA LUI COSTI? ANDREA A SLĂBIT ŞI ARATĂ ŞI MAI BINE DECÂT ŞTIAI!... ",
                  "Le gua a dar laic 👍",
                  " alimente pe care NU ai voie să le ratezi la micul dejun    ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup   ",
                  "Dragilor, sambata seara la 19.00 fiti pe 6 TV :) ( daca nu reusiti urmeaza si online emisiunea surpriza) — feeling happy",
                  "Lucruri pe care NU le ştiai despre sexul oral    ",
                  "Am apreciat un videoclip pe @YouTube de la @alexgavriliu,  Ce se intampla atunci cand traiesti in regrete.",
                  "Am apreciat un videoclip pe @YouTube,  Delia feat. Kaira - Pe aripi de vant (by KAZIBO)",
                  " alimente pe care NU ai voie să le ratezi la micul dejun ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup ",
                  "Lucruri pe care NU le ştiai despre sexul oral ",
                  "Dar sa fiti foarte sinceri :* ",
                  "RT @KabaAdrian1997: Am apreciat un videoclip pe @YouTube de la @lextubee,  Simulator Games - Street Cleaning Simulator",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Substance Painter 1.0 Launch Trailer",
                  "Va asteptam pe la noi ! ",
                  " Klaus Iohannis despre cele șase case pe care le are: Le-am cumpărat prin muncă cinstită:… ",
                  "DATĂ AFARĂ de la ACASĂ TV, REVINE din nou pe MICILE ECRANE! UNDE şi CÂND va APĂREA IOANA MARIA MOLDOVAN!... ",
                  "RT @CurajTV: VIDEO:  Vrea liniște pe stradă, nu să cînte tobele ;-)",
                  "O femeie s-a arătat deranjată de doi tineri care cîntau... ",
                  "Detalii despre noul iPad ajung pe internet chiar de la Apple ",
                  "@ioskap de ce nu ziceti pe bune pe unde umbla astia doi? :)",
                  " alimente pe care NU ai voie să le ratezi la micul dejun ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup ",
                  "Lucruri pe care NU le ştiai despre sexul oral ",
                  "pseudo-scriitoarele astea inca is si minciunoase pe deasupra :))) umbelievable.",
                  "Vale do Catimbau | PE       ",
                  "Stephanie Valenzuela: “Sí me gusta George Forsyth”  ",
                  " alimente pe care NU ai voie să le ratezi la micul dejun  ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup  ",
                  "Nomad pe bicicletă: Dealul Bujoarei – Țebea – Crișan – Brad – Luncoiu de Sus – Deva, ziua III ",
                  "Lucruri pe care NU le ştiai despre sexul oral  ",
                  "O noua interventie pe reteaua de apa – 17 strazi vor fi afectate ",
                  "O noua interventie pe reteaua de apa – 17 strazi vor fi afectate ",
                  "@KrypplerOficial Bine boss, uite intru si eu pe twitter de 3 ori pe an:))",
                  "pseudo-scriitoarele astea inca is si minciunoase pe deasupra :))) unbelievable.",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Un Cedrea pe seară!!!",
                  "https://t.co/6PuAnw4R16 ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Prin ignoranță și delăsare, valorile românești își estompează strălucirea pe zi ce trece. Iar odată cu ele se... ",
                  "@Sorin_Patiu Nu, dar acum parazitează CNSAS, publică nişte cărţi aproape scrise de alţii. Un bou.",
                  "Am postat o fotografie nouă pe Facebook ",
                  "RT @Netjoven: ¿Benjamín Lukovski y Stephanie Valenzuela en una salida? ¿Y George Forsyth?   ",
                  " alimente pe care NU ai voie să le ratezi la micul dejun   ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup   ",
                  "Lucruri pe care NU le ştiai despre sexul oral   ",
                  " alimente pe care NU ai voie să le ratezi la micul dejun ",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup ",
                  "@seeyeasucker meh...pe mn ma enerveaza ca se aduna toata copchilaraia babele si taganii din iasi acolo....da ei nu stiu ce cauta qcolo...:))",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Lucruri pe care NU le ştiai despre sexul oral ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "¿Benjamín Lukovski y Stephanie Valenzuela en una salida? ¿Y George Forsyth? ",
                  "Mi-am dat seama ca noi oamenii ne nastem in zambet, dar murim in iubiri, chiar daca vom cadea in genunchi,... ",
                  "@ludditus să mă cac pe android, oricum.",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "ALEGERI PREZIDENȚIALE 2014. Elena Udrea: „Îl dau jos pe Victor Ponta într-o săptămână” ",
                  "Cum promovează Michelle Obama alimentaţia sănătoasă? Clipul a devenit viral pe Internet ",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Minecraft: The Code - Invazia CREEPY ",
                  "In lipsa unei pisicute dragalase sau unui clip cu bebelusi, va supunem atentiei pe fetele de la HAIM, clar? ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Succesul in afaceri este o calatorie, nu o destinatie.",
                  "iti doresc sa calatoresti  si sa te bucuri pe drumul... ",
                  "Un tip cam beat, il intreaba pe un trecator: ",
                  "- Unde sunt? ",
                  "- Pe strada Unirii. ",
                  "- Lasa detaliile! In ce oras?",
                  "Cata Prostie poate exista in lumea asta!😒il astept pe Fay si pur si simplu nu-mi vine sa cred ce vad acolo,pffiu....",
                  "Hoje vai dar gerodie! Ohhhhhhh yhea!",
                  "Bine zis,Dar si daca nu risti nu castigi󾍇 ",
                  "Once Upon a Time : Intalniri si Magie: Vestile bune vin mereu primele : cand Emma Swan il invita pe Killian Jo... ",
                  "ce culoare au chiloteii de pe tine? — transparenti=))))))))) ",
                  "A desfiintat-o pe fosta sotie dupa divort, dar acum face declaratii surprinzatoare: De fapt, a fost minunat sa... ",
                  "A desfiintat-o pe fosta sotie dupa divort, dar acum face declaratii surprinzatoare: De fapt, a fost minunat sa... ",
                  "@rogim08 alta ii treaba acolo. sa se screama prin ms word, da' nu pe facebook cu pretentii de mare scriitoare :)",
                  "Cel mai dragut citat sau mesaj? — Citat:Gelozia ar trebui sa dovedeasca afectiunea si grija ce ti-o port.. pe la... ",
                  "Stephanie Valenzuela: “Sí me gusta George Forsyth”  ",
                  "Christian Bale l-ar putea interpreta pe Steve Jobs in mega productia Sony ",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Minecraft Survival Game Ep.4",
                  "@itmorar Rareş Bogdan are ca invitați pe Bichir şi Oreste, când subiectul e Ardealul. ",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Minecraft TheEnchatamentCrafters Ep.1 Primul",
                  "@Sorin_Patiu face şi el ce poate, îi invită pe cei care vin.",
                  "Bătălie pe muchie de cuţit între Medina şi Slater la Campionatul Mondial de surfing  - ",
                  "Am apreciat un videoclip pe @YouTube,  [NvA]K1k3r aka [NvA]Olympic",
                  "RT @haharalambie: @nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se baze…",
                  "RT @haharalambie: @nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se baze…",
                  "RT @GabytzaBuga: Cata Prostie poate exista in lumea asta!😒il astept pe Fay si pur si simplu nu-mi vine sa cred ce vad acolo,pffiu....",
                  "Chiar asa prosti ii cred pe cetateni, premierul Ponta?",
                  "https://t.co/SZa3vb9LB5 ",
                  " : Ultimate Pandemic Virus Kit Module- 2 Person",
                  "Ultimate Pandemic Virus Kit Module- 2 Pe... ",
                  "“@radusmall: Atatea mari civilizatii s-au perindat prin Romania si, tot cei mai necivilizati din Europa suntem.” Da, dar nu au rămas... :)",
                  "@sandman_ro @MihaiHristea In sfârșit barbugiu' l-a găsit pe dracu' gol și ce sa vezi, nici nu era greu, lucrează la TVR e @dragospatraru! :D",
                  "I liked a @YouTube video from @zmenta  ANALFABEȚII de pe Facebook / STATUSURI PENIBILE ",
                  "RT @GabytzaBuga: Cata Prostie poate exista in lumea asta!😒il astept pe Fay si pur si simplu nu-mi vine sa cred ce vad acolo,pffiu....",
                  "Ghete stil UGG din piele eco.Pentru mai multe modele si comenzi dati click pe link:... ",
                  "Revoltă în cartier! Focar de infecţie şi bordel pe un şantier abandonat din Ploieşti ",
                  "DETALII AICI:... ",
                  "URGENTA MAXIMA: Donatii pentru 2 pisoi de maxim 4 saptamani bolnavi de rinotraheita pe care i-am preluat astazi... ",
                  " lucruri pe care să NU le faci când copilul este nervos - ",
                  "Cât ar rezista colonia marţiană preconizată de proiectul Mars One? Un studiu arată ce soartă i-ar aştepta ",
                  "@hramella Atunci incearca norocu la colegiu de arte plastice, deseori studentii nu au ce face cu lucrarile, pe cuvint",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Rotariu nu a mai impresionat, dar Stoican are încredere în el: Poate ajunge la echipa naţională  ",
                  "Am publicat 4 fotografii pe Facebook în albumul Octombrie 2014 ",
                  "Cum promovează Michelle Obama alimentaţia sănătoasă? Clipul a devenit viral pe Internet  ",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Asu si Morgana feat Elis Armeanca -SAGAPO ( 2014 )",
                  "VIDEO! De ce numai unii oameni se îmbolnăvesc de cancer? Răspunsul pe care îl așteptai! ",
                  "Am apreciat un videoclip pe @YouTube de la @ukf,  Eptic - Dimension 7",
                  "Doamne, ce-s de proasta ca am incheiat contract pe un an.",
                  "Alegerile nu sunt concurs de copiat.",
                  "Daca s-ar da concurs, azi Ponta i-ar bate pe toti si la fizica si la... ",
                  "Castelul Corvinilor devine mai scump pentru turişti din 2015. Nunta în castel, pe primul loc în topul chiriilor ",
                  "Ma uitam pe programul TV. 02:00 - Antena 1 - Închiderea programului. Ce șansă ratată de a depăși ProTV-ul, of of.",
                  "Ma jurasem ca renunt la rap",
                  "Dar nu ma pot opri din scris",
                  "Eu is chiar nebun la cap clar",
                  "Mi-am promis mie si v-am... ",
                  "@ludditus rahatul de LG mi-a creat nevoia de a face backup cu Titanium pe external SD. nu reușesc, nu e în stare?",
                  "Trebuie s-o vedeti si pe asta si mai ales de ciitit mesajul ! &lt;3 ",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Claudia - Plange mama",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  Zoids Capítulo 12 Completo Audio Latino l",
                  "Si cu deditatie pt fetele care se omoarauna pe ala,va pupacesc minozatelor ",
                  "”Vă rog, luați-l înapoi pe domnul Alimente... Aaa, îl cheamă Calimente? Domnul Mihăiță!”. Gâdea, având umor în direct! Delirium tremens",
                  "@MihaiHristea @sandman_ro @dragospatraru Preferam sa ne calificam la ultimele campionate mondiale și europene, fie chiar și cu el pe banca!",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube,  O.R.T. - Mary Elizabeth McGlynn (Silent Hill:",
                  "Cei mai activi, cele mai frumoase manifeste vor fi premiate pe măsură! :)... ",
                  "Bogdan on Cum fac un sondaj de opinie pe pagina de Facebook ? ",
                  "Senzationalu' domnu' Dan a uitat cind il pupa gretos in cur pe Basescu la OTV!",
                  "Are cineva prin casă sau pe la bunici o mașină de scris funcțională.?  E important",
                  "@RomulusON @sandman_ro @dragospatraru Pai fix asta s-antamplat: cu el pe banca ne-am calificat la Euro2000 si 2008!",
                  "Dai un ban, dar stii ca nu-l mai ai.",
                  "Am publicat 20 fotografii pe Facebook în albumul La Targul International Tehnic - TIB 2014 ",
                  "Prefectul de Suceava: L-am informat pe Printul Paul ca nu-i pot fi date padurile de la Brosteni ",
                  "Ah, dulce cafe creme, Amelie si sarutarideduminica pe strada mea favorita din lumea intreaga... ",
                  "Am publicat 3 fotografii pe Facebook în albumul 15.10.2014-Tura Steluta ",
                  "Am apreciat un videoclip pe @YouTube,  Ambuteiaj [Sector 7]",
                  "Ceea ce se întâmplă pe A3 e incredibil! Să vorbești în halul ăla cu șeful comisiei Siguranței Naționale e... Prea mult chiar și pt pastor!!",
                  "@adriano_qld Calimente doarme pe el ca un bivol...",
                  "@MihaiHristea @sandman_ro @dragospatraru Ptiu, am greșit, nu cu el pe banca, cu el la cazino iar cu tinerii la mondiale, na e bine acu'? :))",
                  "lacrimă de gând",
                  "nu am intrebat niciodată",
                  "pasărea de noapte",
                  "de ce îşi strigă bucuria",
                  "pe sufletul meu",
                  "am închis... ",
                  "Straja. Parc de aventură. Distracție pe măsură ",
                  " face spume la  calm mai baiete iau usor, stim ca sunteti disperati dar calm!!",
                  "O statiune montana din Romania ascunde ZONA NEMURIRII: Apa este unica pe TERRA ",
                  "@MihaiHristea @sandman_ro @dragospatraru Vreau o naționala care sa nu joace cu steagul altei tari în dreptul inimii, dar cu tineri în teren!",
                  "@MihaiHristea Nu fii trist, il ia si pe fii-su cu el la arabi! :))) Sa maninca si gura lui ceva... @RomulusON @dragospatraru",
                  "Pe pe pe pe pe pe pe pe pe pe pe pe ",
                  "Scandal pe Prelungirea Bradului. Disputa intre locatari din cauza uscatorului ",
                  "@albihetemi POPO QATY PE NGOJ",
                  "Fostul sef al comisiei SIE: “Ținta e Melescanu. A depasit pe cine nu trebuie” ",
                  "Scade numarul de alegatori de pe listele electorale  via @-",
                  "Am adăugat Plum Polka Dot Tutu Skirt la vânzare pe Stardoll. Aruncă o privire la ",
                  "Bateria care ar putea scoate automobilul cu benzină de pe stradă: se încarcă până la 70% în două minute | adevarul.ro ",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi ",
                  "Monica Macovei: Ce il leaga pe Victor Ponta de Ovidiu Tender?  via @-",
                  " bate  3 - 0 în Ligã pe  ",
                  "@sandman_ro @MihaiHristea @dragospatraru Ăștia nu mănâncă dar în schimb citesc...cărțile de joc! :)))",
                  "Scade numarul de alegatori de pe listele electorale ",
                  "Monica Macovei: Ce il leaga pe Victor Ponta de Ovidiu Tender? ",
                  "Klaus Iohannis: Prin felul simplu, dar totuși aparte prin care vă arătați susținerea și sprijinul necondiționat... ",
                  "Eu le zambeam la toti le vorbeam amabil",
                  "Ca suntem toti culpabili de-a fii toti capabili",
                  "Dar ei mi-au zis probabil... ",
                  "@aiurea parcă în KitKat o app NU mai poate scrie într-un folder oarecare pe SD card extern. Cum dracu de merge? A hăcuit LG ceva?",
                  "RT @tuitChollywood: Stephanie Valenzuela: “Sí me gusta George Forsyth”  ",
                  ".000 de copii traiesc cu un venit de sub 530 lei pe membru de familie  via @-",
                  "RĂZBOI pe FAŢĂ între BIANCA DRĂGUŞANU şi IULIA ALBU! Şi-au ARUNCAT VORBE GRELE! | FOTO &gt;&gt;  ",
                  "@AlexBartis nu chiar. Subiectiv probabil, imi place mai mult. Cu marimea nu e problema la mine. Cam scumpicel dar nah.",
                  ".000 de copii din Romania traiesc in familii cu un venit de sub 530 lei pe membru de familie ",
                  "Marirea numarului de vizitatori pe site -- ReTweet pls ",
                  "Șelaru: „Nu cred că se pune problema că îl «sapă» cineva pe Liviu Andrieș…” ",
                  "Pe  găsești cele mai noi știri!",
                  "NU RATA ziarul de azi plus o carte la un preț special! ",
                  "Klaus Iohannis a șocat pe toată lumea când a spus că profesorii care nu și-au... ",
                  "Klaus Iohannis a șocat pe toată lumea când a spus că profesorii care nu și-au... ",
                  "Romanii din afara il voteaza pe @KlausIohannis @KlausJohannis ",
                  "Am apreciat un videoclip pe @YouTube,  Nelson Mondialu '' un partzulet un elefant ''",
                  "@MoiseGuran daca la triplează fac romi copii si beau banii, dar la atâta vodca poate mai scapă vreun copil.",
                  "Am apreciat un videoclip pe @YouTube de la @daniel_gomoescu,  da-te-n pula mea ca ma legani cu nervi",
                  "Solisti de pe trei continente la Timisoara Muzicala  via @-",
                  "Care e rochia/costumul pe care l-ai alege la un eveniment? — https://t.co/eLqo8fKKTZ ",
                  "@ludditus nu știu, probabil că nu mi-l afișa dacă nu putea scrie în el. bine, am rulat și asta înainte, dar nu-s convins că a ajutat --&gt;",
                  "Solisti de pe trei continente la Timisoara Muzicala ",
                  "RT @componentesh:  bate  3 - 0 în Ligã pe  ",
                  "RT @componentesh:  bate  3 - 0 în Ligã pe  ",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi   ",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi ",
                  "Fă-ți cont pe Globallshare și urmărește emisiunile săptămânale pe care le realizăm despre agricultura românească,... ",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi ",
                  "Ce vrea un bărbat în pat, dar nu îţi spune (I) ",
                  "Am postat o fotografie nouă pe Facebook ",
                  "Am postat o fotografie nouă pe Facebook "]