module.exports = ["Deci sunt barbatul magic! Am facut supa cu galusti fara galusti!",
                  "S-au zdrobit toate in #plm.",
                  "@ilMircu ar fi mersi de minune. Dar se serveau in locatii diferite :))",
                  "Am postat o fotografie nouă pe Facebook http://t.co/HY0DV3zVv2",
                  "Am postat o fotografie nouă pe Facebook http://t.co/aoZE2wIU1M",
                  "Blogsale: RO:         Primul meu blogsale, cu lucruri pe care vreau sa le dau, pentru  a face loc altora. Pret... http://t.co/KHjzRP0uAH",
                  "Toţi românii de pe tumblr să dea reblog. http://t.co/gOLxcuJzoF",
                  "Peste 80 de persoane aflate într-o ambarcaţiune în derivă, salvate de poliţiştii de frontieră https://t.co/4P5NZAtuun",
                  "Am apreciat un videoclip pe @YouTube de la @playgamepro, http://t.co/VmnJdEvb7f [SA:MP] W/ KTUD0R | Trupa DILIE",
                  "Tocmai am cumpărat Denim Street Shirt, White Fall Sweater pe Stardoll. Aruncă o privire în Suite-ul meu! http://t.co/BbwZ6G9E1I",
                  "@RocioBelen001 PE LI CU LON ♥",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/JG3rcJlOxT Simulator - City Bus Simulator München #1 - Citybus Simulator München",
                  "ALEGERI PREZIDENȚIALE 2014. Elena Udrea: „Îl dau jos pe Victor Ponta într-o săptămână” http://t.co/nWxyudQw6h #stiri",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/ZeAGG3tflr Cum arata un BIOS si setarile BIOS-ului",
                  "Viata ar putea fi minunata daca oamenii te-ar lasa in pace !  Charlie Chaplin ",
                  " Salut pe toti cei pe  care... http://t.co/b2Pyq4w0nM",
                  "...în câteva săptămâni am să urc pe youtube un proiect de Spoken Poetry semnat Elena Netcu!",
                  "Poezie și Trăiri http://t.co/lrqitq0PS8",
                  "O MAI ŢII MINTE PE BULGĂROAICA LUI COSTI? ANDREA A SLĂBIT ŞI ARATĂ ŞI MAI BINE DECÂT ŞTIAI!... http://t.co/p6t5MvgKtE",
                  "#Accenture: MC-Risk #Management, Financial #Services Regulatory Compliance, PE&amp;CE; Consultant + in #NewYork #job http://t.co/zpwBx4nvch",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/frrWXLQqrp",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/GZ69ZP5AAj",
                  "Viața le 'mparte mereu așa, totul se 'ntoarce asupra ta. Poți fugi dar nu te poți ascunde, soarta te găsește oriunde ;)",
                  "@nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se bazeaza pe capital.",
                  "@nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se bazeaza pe capital.",
                  "Am postat o fotografie nouă pe Facebook http://t.co/hHh5hrUuX1",
                  "Gabriel Cotabiţă - Pagină oficială a fost pe la Discotecă într-o... http://t.co/qI7wEbuJ1m",
                  "Un primar vrea interzicerea reclamelor verzi la farmacii: Ii agreseaza vizual pe soferi http://t.co/XylVuUZtLI",
                  "Urgie pe Himalaya: Cel putin 17 alpinisti si serpasi au murit din cauza vremii http://t.co/0nufLWUBe8",
                  "Cât ne costă o sinecură la UNESCO: 62.400 euro pe an | Romania Libera http://t.co/nh9kilXHj6",
                  "Am postat o fotografie nouă pe Facebook http://t.co/PUTxL2Mbk0",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/4l8b3Q7Vbp citeva explicatii despre setarile din bios",
                  "@alinaconst Da. E doar o bucurie trista pe care o traiesc. Viata merge mai inainte. Asa am fost educat. Am predat si mi-am predat o lectie.",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/zA54q31HxW Substance Painter 1 - Getting Started 01 - UI",
                  "O MAI ŢII MINTE PE BULGĂROAICA LUI COSTI? ANDREA A SLĂBIT ŞI ARATĂ ŞI MAI BINE DECÂT ŞTIAI!... http://t.co/c0xjgTjgt2",
                  "O MAI ŢII MINTE PE BULGĂROAICA LUI COSTI? ANDREA A SLĂBIT ŞI ARATĂ ŞI MAI BINE DECÂT ŞTIAI!... http://t.co/963B1Zav5S",
                  "Le gua a dar laic 👍",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/su5WunTwD1 #stiri #romania #politica",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/kL2veQf87Q #stiri #...",
                  "Dragilor, sambata seara la 19.00 fiti pe 6 TV :) ( daca nu reusiti urmeaza si online emisiunea surpriza) — feeling happy",
                  "Lucruri pe care NU le ştiai despre sexul oral http://t.co/ct6kifoHG7 #stiri #romania #politica",
                  "Am apreciat un videoclip pe @YouTube de la @alexgavriliu, http://t.co/eazSEhBQ8C Ce se intampla atunci cand traiesti in regrete.",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/2Teve9EZVf Delia feat. Kaira - Pe aripi de vant (by KAZIBO)",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/mAthwYs54A",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/k94jbHdhmc",
                  "Lucruri pe care NU le ştiai despre sexul oral http://t.co/DWHO8NgO9b",
                  "Dar sa fiti foarte sinceri :* http://t.co/HOMevkbheI",
                  "RT @KabaAdrian1997: Am apreciat un videoclip pe @YouTube de la @lextubee, http://t.co/FdqZlPirrh Simulator Games - Street Cleaning Simulator",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/V8iQAA9G3X Substance Painter 1.0 Launch Trailer",
                  "Va asteptam pe la noi ! http://t.co/8eM9lJkKDA",
                  "#StiriDeUltimaOra Klaus Iohannis despre cele șase case pe care le are: Le-am cumpărat prin muncă cinstită:… http://t.co/3Ll0FeYdY4",
                  "DATĂ AFARĂ de la ACASĂ TV, REVINE din nou pe MICILE ECRANE! UNDE şi CÂND va APĂREA IOANA MARIA MOLDOVAN!... http://t.co/4Vhmtf5QGv",
                  "RT @CurajTV: VIDEO:  Vrea liniște pe stradă, nu să cînte tobele ;-)",
                  "O femeie s-a arătat deranjată de doi tineri care cîntau... http://t.co…",
                  "Detalii despre noul iPad ajung pe internet chiar de la Apple http://t.co/UCs6rWUWHV",
                  "@ioskap de ce nu ziceti pe bune pe unde umbla astia doi? :)",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/FQurhOnuZK",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/dkYHXacc8r",
                  "Lucruri pe care NU le ştiai despre sexul oral http://t.co/QGjnr3fh6K",
                  "pseudo-scriitoarele astea inca is si minciunoase pe deasupra :))) umbelievable.",
                  "Vale do Catimbau | PE #picoftheday #bestoftheday #vialactea #milkyway #igersrecife #igerspernambuco… http://t.co/bU7EHNHu6u",
                  "Stephanie Valenzuela: “Sí me gusta George Forsyth” http://t.co/UeGqzd4136 #espectaculos",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/1nPVf0oYnv #stiri",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/62OB3FnxRI #stiri",
                  "Nomad pe bicicletă: Dealul Bujoarei – Țebea – Crișan – Brad – Luncoiu de Sus – Deva, ziua III http://t.co/Kwd68QjBrV",
                  "Lucruri pe care NU le ştiai despre sexul oral http://t.co/KlnXa8P1Bf #stiri",
                  "O noua interventie pe reteaua de apa – 17 strazi vor fi afectate http://t.co/GKGxrXK1HE",
                  "O noua interventie pe reteaua de apa – 17 strazi vor fi afectate http://t.co/b4r6p75Zma",
                  "@KrypplerOficial Bine boss, uite intru si eu pe twitter de 3 ori pe an:))",
                  "pseudo-scriitoarele astea inca is si minciunoase pe deasupra :))) unbelievable.",
                  "Am postat o fotografie nouă pe Facebook http://t.co/4GyXYrDLnN",
                  "Am postat o fotografie nouă pe Facebook http://t.co/IuHLmrFvZU",
                  "Un Cedrea pe seară!!!",
                  "https://t.co/6PuAnw4R16 http://t.co/hCKA3livfh",
                  "Am postat o fotografie nouă pe Facebook http://t.co/kO62Ez69qA",
                  "Am postat o fotografie nouă pe Facebook http://t.co/c7WYZ8cYtk",
                  "Prin ignoranță și delăsare, valorile românești își estompează strălucirea pe zi ce trece. Iar odată cu ele se... http://t.co/JS6Mq0T130",
                  "@Sorin_Patiu Nu, dar acum parazitează CNSAS, publică nişte cărţi aproape scrise de alţii. Un bou.",
                  "Am postat o fotografie nouă pe Facebook http://t.co/WqpYyvU5R9",
                  "RT @Netjoven: ¿Benjamín Lukovski y Stephanie Valenzuela en una salida? ¿Y George Forsyth?   http://t.co/tmbFQaJeaF",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/u0EBce4V0U #stiri #romania",
                  "Am postat o fotografie nouă pe Facebook http://t.co/jrS3DTkQ0d",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/8pIRjaKDxR #stiri #...",
                  "Lucruri pe care NU le ştiai despre sexul oral http://t.co/VAsMaqeiPy #stiri #romania",
                  " alimente pe care NU ai voie să le ratezi la micul dejun http://t.co/DyMgAh1rtV",
                  "Irina Begu a eliminat-o pe Ekaterina Makarova, locul 12 WTA, si s-a calificat in sferturile Kremlin Cup http://t.co/kcY0fToTxO",
                  "@seeyeasucker meh...pe mn ma enerveaza ca se aduna toata copchilaraia babele si taganii din iasi acolo....da ei nu stiu ce cauta qcolo...:))",
                  "Am postat o fotografie nouă pe Facebook http://t.co/sI4KNR3TgD",
                  "Lucruri pe care NU le ştiai despre sexul oral http://t.co/UqCfcBZgRN",
                  "Am postat o fotografie nouă pe Facebook http://t.co/ELHQaYkHek",
                  "¿Benjamín Lukovski y Stephanie Valenzuela en una salida? ¿Y George Forsyth? http://t.co/H6QZroIsm9",
                  "Mi-am dat seama ca noi oamenii ne nastem in zambet, dar murim in iubiri, chiar daca vom cadea in genunchi,... http://t.co/hEE5oLwZsg",
                  "@ludditus să mă cac pe android, oricum.",
                  "Am postat o fotografie nouă pe Facebook http://t.co/bCSOrh2uEm",
                  "Am postat o fotografie nouă pe Facebook http://t.co/CBzgrBmfNf",
                  "ALEGERI PREZIDENȚIALE 2014. Elena Udrea: „Îl dau jos pe Victor Ponta într-o săptămână” http://t.co/G3039CmgNV",
                  "Cum promovează Michelle Obama alimentaţia sănătoasă? Clipul a devenit viral pe Internet http://t.co/f2ZqDzrvJK",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/a8PeauW4il Minecraft: The Code - Invazia CREEPY #5",
                  "In lipsa unei pisicute dragalase sau unui clip cu bebelusi, va supunem atentiei pe fetele de la HAIM, clar? http://t.co/K3DrII7ZOY",
                  "Am postat o fotografie nouă pe Facebook http://t.co/WJP30Sspw9",
                  "Succesul in afaceri este o calatorie, nu o destinatie.",
                  "iti doresc sa calatoresti  si sa te bucuri pe drumul... http://t.co/gij2xdt4EK",
                  "Un tip cam beat, il intreaba pe un trecator: ",
                  "- Unde sunt? ",
                  "- Pe strada Unirii. ",
                  "- Lasa detaliile! In ce oras?",
                  "Cata Prostie poate exista in lumea asta!😒il astept pe Fay si pur si simplu nu-mi vine sa cred ce vad acolo,pffiu....",
                  "Hoje vai dar gerodie! Ohhhhhhh yhea!",
                  "Bine zis,Dar si daca nu risti nu castigi󾍇 http://t.co/fJqbktpDQQ",
                  "Once Upon a Time : Intalniri si Magie: Vestile bune vin mereu primele : cand Emma Swan il invita pe Killian Jo... http://t.co/iKKnPySqjc",
                  "ce culoare au chiloteii de pe tine? — transparenti=))))))))) http://t.co/jqjl0hs1HV",
                  "A desfiintat-o pe fosta sotie dupa divort, dar acum face declaratii surprinzatoare: De fapt, a fost minunat sa... http://t.co/x4PpoR2jFG",
                  "A desfiintat-o pe fosta sotie dupa divort, dar acum face declaratii surprinzatoare: De fapt, a fost minunat sa... http://t.co/x4PpoR2jFG",
                  "@rogim08 alta ii treaba acolo. sa se screama prin ms word, da' nu pe facebook cu pretentii de mare scriitoare :)",
                  "Cel mai dragut citat sau mesaj? — Citat:Gelozia ar trebui sa dovedeasca afectiunea si grija ce ti-o port.. pe la... http://t.co/LMkPdXU1mZ",
                  "Stephanie Valenzuela: “Sí me gusta George Forsyth” http://t.co/zT1VMzq1LP #entretenimiento",
                  "Christian Bale l-ar putea interpreta pe Steve Jobs in mega productia Sony http://t.co/VagIUiRexS",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/c6qxuAC0bj Minecraft Survival Game Ep.4",
                  "@itmorar Rareş Bogdan are ca invitați pe Bichir şi Oreste, când subiectul e Ardealul. #noapteaminții",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/azU4PtP03W Minecraft TheEnchatamentCrafters Ep.1 Primul",
                  "@Sorin_Patiu face şi el ce poate, îi invită pe cei care vin.",
                  "Bătălie pe muchie de cuţit între Medina şi Slater la Campionatul Mondial de surfing  - http://t.co/gEh89two0w",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/YOwOVjxAxE [NvA]K1k3r aka [NvA]Olympic",
                  "RT @haharalambie: @nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se baze…",
                  "RT @haharalambie: @nashu @ZDZero daca donam sange, cu ajutoru bonurilor de masa puteam cumpara actiuni la Billa, dar-n cartier totu se baze…",
                  "RT @GabytzaBuga: Cata Prostie poate exista in lumea asta!😒il astept pe Fay si pur si simplu nu-mi vine sa cred ce vad acolo,pffiu....",
                  "Chiar asa prosti ii cred pe cetateni, premierul Ponta?",
                  "https://t.co/SZa3vb9LB5 http://t.co/WzrutgRrlw",
                  "http://t.co/LbUf7K3Yhd : Ultimate Pandemic Virus Kit Module- 2 Person",
                  "Ultimate Pandemic Virus Kit Module- 2 Pe... http://t.co/OwgUlnJnG9",
                  "“@radusmall: Atatea mari civilizatii s-au perindat prin Romania si, tot cei mai necivilizati din Europa suntem.” Da, dar nu au rămas... :)",
                  "@sandman_ro @MihaiHristea In sfârșit barbugiu' l-a găsit pe dracu' gol și ce sa vezi, nici nu era greu, lucrează la TVR e @dragospatraru! :D",
                  "I liked a @YouTube video from @zmenta http://t.co/5ukRsAPeci ANALFABEȚII de pe Facebook / STATUSURI PENIBILE #23",
                  "RT @GabytzaBuga: Cata Prostie poate exista in lumea asta!😒il astept pe Fay si pur si simplu nu-mi vine sa cred ce vad acolo,pffiu....",
                  "Ghete stil UGG din piele eco.Pentru mai multe modele si comenzi dati click pe link:... http://t.co/BV1CXx8nPd",
                  "Revoltă în cartier! Focar de infecţie şi bordel pe un şantier abandonat din Ploieşti ",
                  "DETALII AICI:... http://t.co/JpIjZD1MU5",
                  "URGENTA MAXIMA: Donatii pentru 2 pisoi de maxim 4 saptamani bolnavi de rinotraheita pe care i-am preluat astazi... http://t.co/Lod9QDMIvz",
                  " lucruri pe care să NU le faci când copilul este nervos - http://t.co/vQv7P1sVNu",
                  "Cât ar rezista colonia marţiană preconizată de proiectul Mars One? Un studiu arată ce soartă i-ar aştepta http://t.co/wuslu6nKDj",
                  "@hramella Atunci incearca norocu la colegiu de arte plastice, deseori studentii nu au ce face cu lucrarile, pe cuvint",
                  "Am postat o fotografie nouă pe Facebook http://t.co/oAKvXHyPOO",
                  "Rotariu nu a mai impresionat, dar Stoican are încredere în el: Poate ajunge la echipa naţională http://t.co/EApNiYn68e #stiri",
                  "Am publicat 4 fotografii pe Facebook în albumul Octombrie 2014 http://t.co/V94LHT8vBr",
                  "Cum promovează Michelle Obama alimentaţia sănătoasă? Clipul a devenit viral pe Internet http://t.co/oZOw9BeKun #stiri",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/qtvHSiLSXW Asu si Morgana feat Elis Armeanca -SAGAPO ( 2014 )",
                  "VIDEO! De ce numai unii oameni se îmbolnăvesc de cancer? Răspunsul pe care îl așteptai! http://t.co/2yA8L4j0BP",
                  "Am apreciat un videoclip pe @YouTube de la @ukf, http://t.co/icwYrpzDuU Eptic - Dimension 7",
                  "Doamne, ce-s de proasta ca am incheiat contract pe un an.",
                  "Alegerile nu sunt concurs de copiat.",
                  "Daca s-ar da concurs, azi Ponta i-ar bate pe toti si la fizica si la... http://t.co/I8hE5ocrMS",
                  "Castelul Corvinilor devine mai scump pentru turişti din 2015. Nunta în castel, pe primul loc în topul chiriilor http://t.co/crKmRbYjRA",
                  "Ma uitam pe programul TV. 02:00 - Antena 1 - Închiderea programului. Ce șansă ratată de a depăși ProTV-ul, of of.",
                  "Ma jurasem ca renunt la rap",
                  "Dar nu ma pot opri din scris",
                  "Eu is chiar nebun la cap clar",
                  "Mi-am promis mie si v-am... http://t.co/RQ3uH4LhHf",
                  "@ludditus rahatul de LG mi-a creat nevoia de a face backup cu Titanium pe external SD. nu reușesc, nu e în stare?",
                  "Trebuie s-o vedeti si pe asta si mai ales de ciitit mesajul ! &lt;3 http://t.co/DsRkgenDZK",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/QBpnt64GBG Claudia - Plange mama",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/pqCdQqY7PK Zoids Capítulo 12 Completo Audio Latino l",
                  "Si cu deditatie pt fetele care se omoarauna pe ala,va pupacesc minozatelor http://t.co/sCGdydZLb9",
                  "”Vă rog, luați-l înapoi pe domnul Alimente... Aaa, îl cheamă Calimente? Domnul Mihăiță!”. Gâdea, având umor în direct! Delirium tremens",
                  "@MihaiHristea @sandman_ro @dragospatraru Preferam sa ne calificam la ultimele campionate mondiale și europene, fie chiar și cu el pe banca!",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/DrhOQUhBtT O.R.T. - Mary Elizabeth McGlynn (Silent Hill:",
                  "Cei mai activi, cele mai frumoase manifeste vor fi premiate pe măsură! :)... http://t.co/K8RgsDMfyB",
                  "Bogdan on Cum fac un sondaj de opinie pe pagina de Facebook ? http://t.co/l3jGTxlB3i",
                  "Senzationalu' domnu' Dan a uitat cind il pupa gretos in cur pe Basescu la OTV!",
                  "Are cineva prin casă sau pe la bunici o mașină de scris funcțională.?  E important",
                  "@RomulusON @sandman_ro @dragospatraru Pai fix asta s-antamplat: cu el pe banca ne-am calificat la Euro2000 si 2008!",
                  "Dai un ban, dar stii ca nu-l mai ai.",
                  "Am publicat 20 fotografii pe Facebook în albumul La Targul International Tehnic - TIB 2014 http://t.co/l050rKSA4F",
                  "Prefectul de Suceava: L-am informat pe Printul Paul ca nu-i pot fi date padurile de la Brosteni http://t.co/f5siPodw3U",
                  "Ah, dulce cafe creme, Amelie si sarutarideduminica pe strada mea favorita din lumea intreaga... http://t.co/l9Sy4A2PJu",
                  "Am publicat 3 fotografii pe Facebook în albumul 15.10.2014-Tura Steluta http://t.co/FIylqQRgAF",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/R8UAFlA7cK Ambuteiaj [Sector 7]",
                  "Ceea ce se întâmplă pe A3 e incredibil! Să vorbești în halul ăla cu șeful comisiei Siguranței Naționale e... Prea mult chiar și pt pastor!!",
                  "@adriano_qld Calimente doarme pe el ca un bivol...",
                  "@MihaiHristea @sandman_ro @dragospatraru Ptiu, am greșit, nu cu el pe banca, cu el la cazino iar cu tinerii la mondiale, na e bine acu'? :))",
                  "lacrimă de gând",
                  "nu am intrebat niciodată",
                  "pasărea de noapte",
                  "de ce îşi strigă bucuria",
                  "pe sufletul meu",
                  "am închis... http://t.co/LWnBLeLbh7",
                  "Straja. Parc de aventură. Distracție pe măsură http://t.co/xNxkNyKBby",
                  "#Gadea face spume la #Haznaua3, calm mai baiete iau usor, stim ca sunteti disperati dar calm!!",
                  "O statiune montana din Romania ascunde ZONA NEMURIRII: Apa este unica pe TERRA http://t.co/bxm6m9zDN4",
                  "@MihaiHristea @sandman_ro @dragospatraru Vreau o naționala care sa nu joace cu steagul altei tari în dreptul inimii, dar cu tineri în teren!",
                  "@MihaiHristea Nu fii trist, il ia si pe fii-su cu el la arabi! :))) Sa maninca si gura lui ceva... @RomulusON @dragospatraru",
                  "Pe pe pe pe pe pe pe pe pe pe pe pe http://t.co/ZgV247sHHW",
                  "Scandal pe Prelungirea Bradului. Disputa intre locatari din cauza uscatorului http://t.co/NI1W080ak5",
                  "@albihetemi POPO QATY PE NGOJ",
                  "Fostul sef al comisiei SIE: “Ținta e Melescanu. A depasit pe cine nu trebuie” http://t.co/zRdTDoeycN",
                  "Scade numarul de alegatori de pe listele electorale http://t.co/GUtBK7aPnu via @-",
                  "Am adăugat Plum Polka Dot Tutu Skirt la vânzare pe Stardoll. Aruncă o privire la http://t.co/JunvxoP3uS",
                  "Bateria care ar putea scoate automobilul cu benzină de pe stradă: se încarcă până la 70% în două minute | adevarul.ro http://t.co/f8ZzClsDR3",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/7Gv2ypOAae",
                  "Monica Macovei: Ce il leaga pe Victor Ponta de Ovidiu Tender? http://t.co/mh4KaVq2ZM via @-",
                  "#AVFC bate #AFC 3 - 0 în Ligã pe #SoccerManager http://t.co/vnOuG4Ic7r",
                  "@sandman_ro @MihaiHristea @dragospatraru Ăștia nu mănâncă dar în schimb citesc...cărțile de joc! :)))",
                  "Scade numarul de alegatori de pe listele electorale http://t.co/V7c0Ki1Q17",
                  "Monica Macovei: Ce il leaga pe Victor Ponta de Ovidiu Tender? http://t.co/3xEYmhfpKK",
                  "Klaus Iohannis: Prin felul simplu, dar totuși aparte prin care vă arătați susținerea și sprijinul necondiționat... http://t.co/eflRiv9IyI",
                  "Eu le zambeam la toti le vorbeam amabil",
                  "Ca suntem toti culpabili de-a fii toti capabili",
                  "Dar ei mi-au zis probabil... http://t.co/yrYql8X9io",
                  "@aiurea parcă în KitKat o app NU mai poate scrie într-un folder oarecare pe SD card extern. Cum dracu de merge? A hăcuit LG ceva?",
                  "RT @tuitChollywood: Stephanie Valenzuela: “Sí me gusta George Forsyth” http://t.co/zT1VMzq1LP #entretenimiento",
                  ".000 de copii traiesc cu un venit de sub 530 lei pe membru de familie http://t.co/XRLtRIotAu via @-",
                  "RĂZBOI pe FAŢĂ între BIANCA DRĂGUŞANU şi IULIA ALBU! Şi-au ARUNCAT VORBE GRELE! | FOTO &gt;&gt; http://t.co/r0jzdUAFLk http://t.co/5vNrrlDlyQ",
                  "@AlexBartis nu chiar. Subiectiv probabil, imi place mai mult. Cu marimea nu e problema la mine. Cam scumpicel dar nah.",
                  ".000 de copii din Romania traiesc in familii cu un venit de sub 530 lei pe membru de familie http://t.co/ur5tPuUpJj",
                  "Marirea numarului de vizitatori pe site -- ReTweet pls http://t.co/EjDxBDN9Bf",
                  "Șelaru: „Nu cred că se pune problema că îl «sapă» cineva pe Liviu Andrieș…” http://t.co/y7VUelJe5p",
                  "Pe http://t.co/gbGl5thL2w găsești cele mai noi știri!",
                  "NU RATA ziarul de azi plus o carte la un preț special! http://t.co/sJCaYdyM9j",
                  "Klaus Iohannis a șocat pe toată lumea când a spus că profesorii care nu și-au... http://t.co/XAyOQ3gu0E",
                  "Klaus Iohannis a șocat pe toată lumea când a spus că profesorii care nu și-au... http://t.co/QDJQiKAmCF",
                  "Romanii din afara il voteaza pe @KlausIohannis @KlausJohannis http://t.co/GAGfgmBlmw",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/gQBP3ICQyl Nelson Mondialu '' un partzulet un elefant ''",
                  "@MoiseGuran daca la triplează fac romi copii si beau banii, dar la atâta vodca poate mai scapă vreun copil.",
                  "Am apreciat un videoclip pe @YouTube de la @daniel_gomoescu, http://t.co/CPzExvE2nH da-te-n pula mea ca ma legani cu nervi",
                  "Solisti de pe trei continente la Timisoara Muzicala http://t.co/ZHXRGKIlv2 via @-",
                  "Care e rochia/costumul pe care l-ai alege la un eveniment? — https://t.co/eLqo8fKKTZ http://t.co/Tggb8jGu3Z",
                  "@ludditus nu știu, probabil că nu mi-l afișa dacă nu putea scrie în el. bine, am rulat și asta înainte, dar nu-s convins că a ajutat --&gt;",
                  "Solisti de pe trei continente la Timisoara Muzicala http://t.co/ua28ZXTmnA",
                  "RT @componentesh: #AVFC bate #AFC 3 - 0 în Ligã pe #SoccerManager http://t.co/vnOuG4Ic7r",
                  "RT @componentesh: #AVFC bate #AFC 3 - 0 în Ligã pe #SoccerManager http://t.co/vnOuG4Ic7r",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/ItDgjRVWKR #stiri #romania...",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/eU5WyfzX8r",
                  "Fă-ți cont pe Globallshare și urmărește emisiunile săptămânale pe care le realizăm despre agricultura românească,... http://t.co/890ffnIfBT",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/Om6hBmXTwB",
                  "Ce vrea un bărbat în pat, dar nu îţi spune (I) http://t.co/PAfk7KU46c",
                  "Am postat o fotografie nouă pe Facebook http://t.co/rnF3HoFCMR",
                  "Am postat o fotografie nouă pe Facebook http://t.co/MSaGYLE9uB",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/tRob6921ij #stiri",
                  "Parkinson? Ma scuzati, dar ori sint timpiti, ori n-au un documentarist.",
                  "Asa va arata discul pe care veti putea asculta hip-hop-ul lui Dribbler. Luna asta. http://t.co/Nr9tWmmQ2x",
                  "Cu sânii la înaintare pe Facebook. S-a deazbrăcat și a arătat tot pe INTERNET. Diva de 25 de ani care se iube http://t.co/7fw8bxMJ9y #stiri",
                  "Articol nou Atelier: Fotografia de joi › Bogdan Botofei: Trei http://t.co/lNb8uV6Q5N",
                  "Articol nou Atelier: Interviuri › Doina GiurgiuOana GiurgiuLetiţia Ştefănescu: Fascinaţia de a afla istoria ... http://t.co/GG2zW8bHQl",
                  "Articol nou Atelier: Ceaiul de joi dimineaţă › Ilinca Anamaria Prisăcariu: Dialog la balta cu cerneală http://t.co/GFqsk5ZHOw",
                  "Articol nou Atelier: Din lumea celor mici › Ioana Steluţa Manea: Infinitul e o gaură în inima mea http://t.co/P7UsJYvKYG",
                  "Largueeiiiii (@ Scopus Tecnologia S.A in Recife, PE) https://t.co/UXAtoheLIw",
                  "Zece percheziţii şi zeci de audieri, într-un dosar cu „peşti“ şi prostituate http://t.co/vMnP19tlgz #stiri",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/nl37ZmSFYX EL PRISIONERO MAS TORPE !! - Escaping The Prison |",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/YzvnyzOPh9 #stiri #romania",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/0hrkJ0BEUI Kamelia - Te rog",
                  "Eu... Ea.. Tot aici, dar n-am lipici",
                  "Ea nu ma vrea, se tine asa, ",
                  "Sa ma ajute cinevaaaa!!! http://t.co/gzWsbAZHyi",
                  "@ThaliaWorldMag ce fain!! dar mi se incarca in slow motion :)) la ce rezolutie are nu ma mir; fa mai multe dar mai mici un pic :D",
                  "Variantă SURPRIZĂ pentru postul de selecţioner. Un cuplu de AUR ar urma să-l înlocuiască pe Piţi http://t.co/b3QoYp8GOE",
                  "Ioana Lupea, cat a lucrat la TVR, il invita pe comunistul Vasile Ernu aproape saptamanal. De cand a devenit... http://t.co/SHlyomtZXU",
                  "Un politist sarb il loveste pe Cana de la Albania. http://t.co/oyxj9ZdHKf",
                  "Am apreciat o listă de redare pe @YouTube, http://t.co/rcavD0fnnN stapanii manelelor",
                  "Am postat o fotografie nouă pe Facebook http://t.co/kDVQXNrsDi",
                  "@MihaiHristea @sandman_ro @dragospatraru Bine, o spun pe șleau, Vica nu e balerina, e o virgina, cazinoul nu e casa lu' Satan ci e number1!",
                  "Viorel Mazilu il executa pe Garralda: ”Bacaul e o echipa usor de contracarat, au doua scheme” http://t.co/gguhMb8J4N",
                  "Majoritatea oamenilor au ras de ea cand a intrat pe scena. Vocea ei a uimit toata sala! http://t.co/bx3B9opZ0R",
                  "Niște potriviri atât de perfecte ale gândurilor cuiva pe gândurile tale, încât să nu îți dorești să te afli în... http://t.co/M1lPKexjxP",
                  "@sandman_ro Fratili meu alb, i-ai bestelit pe toti de le-au mers fulgii, dar de imaginea cu Bas care nu poate tine paharul in mana ce zici??",
                  "@sandman_ro Fratili meu alb, i-ai bestelit pe toti de le-au mers fulgii, dar de imaginea cu Bas care nu poate tine paharul in mana ce zici??",
                  "Cu ca-ti te futi pe zii? — Meh...depinde....lunea doar cu 10. Marti,miercuri, joi si vineri cu vreo70 sau 80. Sa... http://t.co/XEHqQ5aygo",
                  "Majoritatea oamenilor au ras de ea cand a intrat pe scena. Vocea ei a uimit toata sala! http://t.co/e334OZFdDy",
                  "@beIIarke ALELUIA, DE PE IGREJA",
                  "@inna_ro ❤ ¡¡LA MULTI ANI ALEXANDRA!! ❤ La multi ani cu fericire, sa pui mâna pe iubire, Și cu fundul pe bani, sănătate și La Multi Ani!",
                  "RT @lequipe: Raymond Domenech : Kurzawa est débile http://t.co/V6TPLtqQX6",
                  "Tu parcă eşti de pe altă planetă, ",
                  "Şi povesteşti de iubirea perfectă... ",
                  "De parcă ea ar exista. ☺❤󾌧 http://t.co/aYWVpu5hHT",
                  "RT @tuitChollywood: Stephanie Valenzuela: “Sí me gusta George Forsyth” http://t.co/UeGqzd4136 #espectaculos",
                  "cum-necum Base a adus-o pe Udrea de la 6,6% la 6,7%",
                  "Pfai ce as vrea sa vad si eu ceva video cu politica de acasa, dar vad ca posturile TV sunt in continuare cu multi ani in urma… recomandari?",
                  "@Mielu8 oho...dar cati nu l-au spurcat :)))",
                  "@MihaiHristea @sandman_ro @dragospatraru Dar niște românași tineri din nu găsim sa cumpăram la nationala ca babalâcii joaca doar ca racu'!:D",
                  "Am postat o fotografie nouă pe Facebook http://t.co/AcyrM6NwZ4",
                  "Dorian Popa - Pe placul tau (Official Video HD) http://t.co/wtkiPYHe8j",
                  "RT @aveconstant: @sandman_ro Fratili meu alb, i-ai bestelit pe toti de le-au mers fulgii, dar de imaginea cu Bas care nu poate tine paharul…",
                  "RT @aveconstant: @sandman_ro Fratili meu alb, i-ai bestelit pe toti de le-au mers fulgii, dar de imaginea cu Bas care nu poate tine paharul…",
                  "RT @sandman_ro: Senzationalu' domnu' Dan a uitat cind il pupa gretos in cur pe Basescu la OTV!",
                  "- Te asteptam pe 31 Octombrie la SPORTIFY - Calea lui Traian nr.68  pentru o petrecere infricosatoare....pentru... http://t.co/djfNdbQJMx",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/f23pqmxHlp Reggae 2013 My Favorite Reggae Remix / Cover Songs",
                  "Cea mai grea luptă este cea care se dă între MINTEA si INIMA ta.",
                  "Niciodată nu stii pe care s-o asculti. — feeling confused",
                  "- Te asteptam pe 31 Octombrie la SPORTIFY - Calea lui Traian nr.68  pentru o petrecere infricosatoare....pentru... http://t.co/zl4R5SBMgF",
                  "- Te asteptam pe 31 Octombrie la SPORTIFY - Calea lui Traian nr.68  pentru o petrecere infricosatoare....pentru... http://t.co/hp9IGNbdRT",
                  "Din cand in cand povestesc pe blog din bucataria zilelor mele. Unele sunt mai bune, altele mai ...ciudate.... http://t.co/GH1sBpKtHe",
                  "Va multumesc pentru aprecierile voastre si dragostea pe care o simt venind dinspre voi.❤️❤️❤️❤️❤️",
                  "Ma lasa dureros... http://t.co/8L2kUrNvCY",
                  "Supernatural Sezonul 10 Episodul 2 Online subtitrat. Pe site-ul nostru vizionezi: Supernatural Sezonul 10... http://t.co/5oRzaLpREu",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/1OXIsmdPLS TeknoAXE's Royalty Free Music - Royalty Free Remix",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/5kA6CPBCIw Grasu XXL - Blanădeurs (Freestyle) (prod. Don Baxter | scratch: DJ",
                  "ALEGERI PREZIDENȚIALE 2014. SONDAJ: Victor Ponta și Klaus Iohannis, la 10 procente diferență. Elena Udrea, pe ... http://t.co/YWi2g1QO6U",
                  "Va multumesc pentru aprecierile voastre si dragostea pe care o simt venind dinspre voi.❤️❤️❤️❤️❤️",
                  "Ma lasa dureros... http://t.co/aKSPjqMoug",
                  "Închisoare pentru vasluianul care a încercat să violeze două bătrâne, dar s-a ales cu o bătaie zdravănă http://t.co/Vr4IZLVECy",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/5jxwd4Nyy0 The Forest | FACECAM | Moartea lui Shelbi #9",
                  "Da' eu ma uit... si puti in mashina a peste bihlit.",
                  "Niam adus aminte... eu j am fost cu pescuitu la Salton Sea pe... http://t.co/qw5jMj7Tb9",
                  "@SLYSOFT unul care sta pe doua scaune cu fundul în aer",
                  "@daniel1266399 @angelitorb_99 @_ImMario_ pe-pe-pe-pe-pentakill",
                  "Oh, ne-am zvârlit, strigându-ne pe nume, ",
                  "unul spre celălalt, şi-atât de iute,",
                  "că timpul se turti-ntre piepturile... http://t.co/HnNtTWTRp3",
                  "S-a dus ziua, iar eu nu am apucat să-i spun un la mulți ani foarte călduros unui om pe care îl admir în taină și... http://t.co/eOHsGGMy2X",
                  "Sa radem :)).Pisica care se aseaza tacticos pe mainile stapanei care tasteaza e maxima http://t.co/h0aXSoKRWc",
                  "@ludditus nu știu, așa apărea în root explorer. dar am apps pe card, camera salvează pozele acolo... cert e că am rezolvat, făcui bkp pe sd",
                  "@ludditus nu știu, așa apărea în root explorer. dar am apps pe card, camera salvează pozele acolo... cert e că am rezolvat, făcui bkp pe sd",
                  "Azi plângem și cerem eliminarea microbuzelor dar mâine o să ne treacă, da? Totuși e mai simplu să ne ia... http://t.co/ICdnz3Bf3R",
                  "Am postat o fotografie nouă pe Facebook http://t.co/xJymLXIU4e",
                  "Am postat o fotografie nouă pe Facebook http://t.co/NMXjqbyirB",
                  "Am postat o fotografie nouă pe Facebook http://t.co/1ucrklVOH2",
                  "Am postat o fotografie nouă pe Facebook http://t.co/EteAP5XpH0",
                  "Prima parte a lucrărilor de resistematizare de pe DN 13 se încheie în cel mult o… http://t.co/j7EmzhgGE0 #brasov",
                  "Am postat o fotografie nouă pe Facebook http://t.co/B4DHgiyI8P",
                  "tramvaiul-de-nu-ma-lasa-pe-mine-sa-dorm-pentru-ca-are-sine-de-indreptat http://t.co/oDK4KvEkNo",
                  "Pe viitor nu acceptam orice harb, da? Sa se intoarca inapoi in Bucuresti, ca era mai bine decat ca acum!... http://t.co/XIoTnObQfe",
                  "Am postat o fotografie nouă pe Facebook http://t.co/qEBotazfOe",
                  "Victorinox Corporate Gifts, Werbeartikel, Artículos promocionales, Articles publicitaires, Firemné darčeky",
                  "https://t.co/WG7HTd8eRw",
                  "pe pe pe pe re re pe pe és perigosaaaaaaa",
                  "@emi_ba @haharalambie e mișto EP-ul, păcat că la vreo două piese o ia rău pe arătura cu versurile, în rest lirica și flow excepționale.",
                  "Am postat o fotografie nouă pe Facebook http://t.co/Ij2LcVdVZD",
                  "@soyunarceus Secseee pe",
                  "Iată care sunt actele pe care trebuie să le depuneţi împreună cu cererea pentru ajutorul de încălzire http://t.co/Pon3ioxOj9",
                  "@RomulusON @sandman_ro @dragospatraru Yo zic sa bei totusi o bere si s-o pui pe Udrea la Nationala, ca-i buna pentru Romania, nu? :))",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/OyHmlcHkoB IONUT CERCEL &amp; PETRICA CERCEL - OMUL CU VALOARE {oficial video} Tel:",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/bPw2aHwjvI Cuvine-se cu adevărat! - Imn Ortodox Bizantin Superb - Glas 5 tetrafon",
                  "Am vizionat prima data #Usturoi intr-un birou cu inca 7 oameni, pe vremea cand inca se puneau intrebari de genu... http://t.co/anWrTCN23d",
                  "Am refuzat să merg la interviul pentru internshipul la Camera Dep., dar încă primesc mailuri de la pers. responsabile. Bun așa.",
                  "FOTO Accident mortal pe centura Oradei. Un mecanic auto a murit în timp ce testa un BMW http://t.co/tLIo80p1jM #oradea",
                  "PD e “deranjat” de campania unionistă a prezidenţiabililor români? OARE? Dar cu legea cum rămâne? http://t.co/eFzjDIQusV",
                  "Am postat o fotografie nouă pe Facebook http://t.co/tPJDeXYKD4",
                  "Am postat o fotografie nouă pe Facebook http://t.co/LY7azlvGhO",
                  "Am postat o fotografie nouă pe Facebook http://t.co/RHGeP6bcco",
                  "Am postat o fotografie nouă pe Facebook http://t.co/ICslOvnrEk",
                  "@MihaiHristea @sandman_ro @dragospatraru Ma gandeam ca daca Piţi o ia pe Nuţi cu el sa-şi arate ţâtele la meci sigur ia campionatu'! :))))))",
                  "@matiascarmonaa PE pE pe pe pero  bueni",
                  "RT @ramontremosa: Ara sóc a la conferència Spanish veto on renewables, organitzada al PE per l'eurodiputat valència @Sebastia_Jordi http:…",
                  "Am postat o fotografie nouă pe Facebook http://t.co/ZlRb2luKQX",
                  "Lecturati pe rand sa ajunga la toata lumea! RT Campania electorală – faza Parkinson : Cătălin Tolontan http://t.co/TG6Owd0HPB",
                  "Am postat o fotografie nouă pe Facebook http://t.co/83coYZ9u4h",
                  "RT @newsbv: Prima parte a lucrărilor de resistematizare de pe DN 13 se încheie în cel mult o… http://t.co/j7EmzhgGE0 #brasov",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/OdMwS6qeBO Florin Salam si Costi de la Timisoara - Misca-te ca o felina [official",
                  "PSD-ul se teme de un nou MĂCEL: Băsescu vrea să-l lege pe Ponta de cel mai mare scandal http://t.co/BP3Kaj3GIs",
                  "Am postat o fotografie nouă pe Facebook http://t.co/m0sl9XbyfM",
                  "Faimoasa aplicatie UBER vine si in Romania. Iata ce farsa au facut Americanii pe seama soferilor... http://t.co/Sb3w53pJkU",
                  " lucruri pe care trebuie sa le faci in fiecare zi daca vrei sa fii fericita – gândul http://t.co/CXF1IuqkGQ",
                  "militianul ioan rus, cel care i-a prins pe platon si arostotel ca au plagiat, trage tare sa ne arate ca e mai... http://t.co/wIeJau1rHU",
                  "Până și învățatul la biofizică pare mai ușor când îl asculți pe Abel http://t.co/tdhVexX1ro",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/Hl4eKvQYuU ARGATU - RASTA LOVE",
                  "Zece percheziţii şi zeci de audieri, într-un dosar cu „peşti“ şi prostituate: Vrancea, ultima ora: Zece... http://t.co/3e8ugPMdNr #stiri",
                  "Pierdem cursa împotriva Ebola?: CSID, ultima ora: Pierdem cursa împotriva Ebola?. Lumea este pe cale să... http://t.co/I084ky9PUQ #stiri",
                  "Am postat o fotografie nouă pe Facebook http://t.co/AmIQr5kpkJ",
                  "A aparut routerul care iti asigura anonimatul pe Internet http://t.co/hi5NrX1cul",
                  "Before&amp;After challange",
                  "Am fost provocat de: Oana Elena B si Catalina Druta. ",
                  "Provoc pe: - http://t.co/l4uBrdO0a9",
                  "GIGI BECALI E ÎN DELIR! ANUNŢ BOMBĂ AL LUI COSTEL GÂLCĂ ÎN MIEZ DE NOAPTE! ",
                  "COSTELINHO L-A FĂCUT PE PATRON SĂ... http://t.co/7IOkb11SI4",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/ly9yipXJQ2 Feli - Cine te crezi? [Official video HD]",
                  "Am postat o fotografie nouă pe Facebook http://t.co/Uhy66g7kFx",
                  "Am postat o fotografie nouă pe Facebook http://t.co/zm9OgeOozE",
                  "ÎI COMENTEAZĂ pe toţi, dar de DATA ASTA a DAT-O CHIAR ea în BARĂ &gt;&gt; http://t.co/6sSsrobEWJ http://t.co/xima2Z36ZK",
                  "ÎI COMENTEAZĂ pe toţi, dar de DATA ASTA a DAT-O CHIAR ea în BARĂ &gt;&gt; http://t.co/6sSsrobEWJ http://t.co/xima2Z36ZK",
                  "ce tristețe pe ăștia care au votat PPDD când văd cum le trec justițiarii la partidele ciocoilor:))) între timp... http://t.co/x76AheEU0I",
                  "I'm at Biblioteca in Caruaru, PE https://t.co/EYSW8I6iLK",
                  "Întăi am văzut ce creează, apoi am cunoscut omul. Ce-i drept doar virtual, dar a fost suficient ca să-i ofer un... http://t.co/EQpMLZWjVL",
                  "Dovada ca Sfanta nu ii iarta pe cei pacatosi :)) http://t.co/dfmoxXVyFw",
                  ":)",
                  "*să ne atingem, a dispărut poke de pe fb. http://t.co/Vsvc2MkCmg",
                  "Chrissy, nu știu cine e bărbatul cu care locuiești, dar nu e Ben. 󾍁 — reading Before I Go to Sleep - A Novel",
                  "Am avut sute de sanse sa fiu fericit dar nu eu am ales fericirea ei, da e adevarat am mai si gresit dar cine nu... http://t.co/4focpJFGM1",
                  "Cele mai educative știri de pe #diez din 15 septembrie http://t.co/fDVPdU5Ufu",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/nfzswFyllm COMENTARII.",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/8GgU75vu53 3 Things Email Subscribers Want From You",
                  "NOAPTE BUNA SI VISE MINUNATE PENTRU TOTI PRIETENII MEI DE PE FACEBOOK!... http://t.co/ZcgXZR4Mti",
                  "Cele mai educative știri de pe #diez din 15 septembrie | #diez http://t.co/nM2l7adqdC via @diez_moldova",
                  "Am postat o fotografie nouă pe Facebook http://t.co/6uGiAC4Lys",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/ITCgyATv1m How To Use Boost Post For Your Facebook Fan Page",
                  "Am postat o fotografie nouă pe Facebook http://t.co/KSSKlHazMh",
                  "Mihai Răzvan Ungureanu şi Gheorghe Flutur prezenţi în Neamţ pentru a-l susţine pe Klaus Iohanis http://t.co/eyhzLdNcEG",
                  "Am postat o fotografie nouă pe Facebook http://t.co/lSM0QL3HVu",
                  "Cele mai educative știri de pe #diez din 15 octombrie... http://t.co/9DMj22pccJ",
                  "Catavencii: Macovei va cîștiga sigur. Un premiu la vreun festival de publicitate: Îi știți pe DJ-ii de la radi... http://t.co/IFxyBjiZwL",
                  "RT @MihaiHristea: @RomulusON @sandman_ro @dragospatraru Yo zic sa bei totusi o bere si s-o pui pe Udrea la Nationala, ca-i buna pentru Roma…",
                  "http://t.co/y7y85MhANJ minecraft pe wiki 0 8 1",
                  "Au fost vorbe grele dar faptele vor vorbi pentru mine :-)",
                  "@aiurea nu stiu, eu nu mai sunt la Realitatea. Dar da, chestia aia e facuta de mine :P",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/qk8kfs56Ud Felicia Georgescu Si afara ploua, ploua",
                  "...”Iată acum crâmpeie dintr-o altă istorie: * La începutul anilor ’90, postul TVR Internaţional era pus pe... http://t.co/WkGbJw8NxG",
                  "Pe Youtube nu este nicidecum un subiect nou. Exista deja multe filmulete in care diversi oameni din toate colt... http://t.co/58vKT4FZq1",
                  "pe Mitrea l-a felicitat ieri cineva? cică a împlinit și ăsta vreo doi ani și ceva!",
                  "Am postat o fotografie nouă pe Facebook http://t.co/oCNKu2l5Uc",
                  "Aviz şoferilor şi bicicliştilor care circulă pe Calea Victoriei. Pedalam azi pe acolo, pe prima banda, lângă... http://t.co/KaRKbVLapg",
                  "Am postat o fotografie nouă pe Facebook http://t.co/ytKbL4pfWf",
                  "BOMBĂ!",
                  "Consuelo l-a chemat pe Adi Mutu la nunta ei!--&gt;&gt;&gt; http://t.co/AoZyWvFDd3 http://t.co/inEurGUbkp",
                  "E nasol sa fii in momentul nepotrivit, la locul nepotrivit... Dar si mai rau e sa nu fii unde ar trebui sa fii sau unde ai vrea sa fii...",
                  "Am apreciat un videoclip pe @YouTube, http://t.co/ghzj8JXk2y Felicia Georgescu Lacrima de jar Studio",
                  "Am postat o fotografie nouă pe Facebook http://t.co/VhTWUuHTpS",
                  "România e pe listă. http://t.co/JdY59XE4jp",
                  "Am postat o fotografie nouă pe Facebook http://t.co/OLU92vqU7u",
                  "Am postat o fotografie nouă pe Facebook http://t.co/3U4eKn6MaP",
                  "Prietenul Mariusică nu are tabletă. Sau, nu avea, deoarece acum o folosește pe-a mea. http://t.co/R13b2vDVwO",
                  "Am postat o fotografie nouă pe Facebook http://t.co/NiFKDslxqR",
                  "@Littleliar98 @sendadeIsis PE PE PE PE PE ;________________________;",
                  "Adaptor pentru obiectivele EF (Canon) pe montura E (Sony NEX), la un preț normal http://t.co/KFkBjjdZBX",
                  "Am postat o fotografie nouă pe Facebook http://t.co/L2SwrKjYJP",
                  "Am postat o fotografie nouă pe Facebook http://t.co/b1keHzsLI0",
                  "@boioglu deci imi place teoria ta ... dar daca libra bank a facut din astea ... sa vezi ce ii injur, cu pule direct",
                  "@boioglu dar ia uite-te tu in IP-urile de la ambele mailuri primite, de unde le-ai primit?",
                  ".am gasit catelusa aceasta pe str Rm Valcea,langa benzinaria Mol,zona Dristor( in fata cofetariei Georgy,s). A... http://t.co/py7ofNZrcp",
                  "Am postat o fotografie nouă pe Facebook http://t.co/8b08KsdprH",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/M9VrvC037s #stiri #romania",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/m7sHAvtSq0 #stiri #romania",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/IAEF7ZugJG #stiri #romania",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/fn42GbhPId #stiri #romania",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/MIZykutozp",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/oTGy4lzez6",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/Op9OsFOGrq",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/TcBcCY6A5b",
                  "Am apreciat un videoclip pe @YouTube de la @ktud0rgames, http://t.co/5jxwd4Nyy0 The Forest | FACECAM | Moartea lui Shelbi #9",
                  "Am postat o fotografie nouă pe Facebook http://t.co/EfyAWvNZXJ",
                  "ONU: Lumea este pe cale să piardă lupta împotriva Ebola http://t.co/wkmIfDn3ES",
                  "http://t.co/wgLVARa6yM - un cont cu o adresă de mail. here beta pt android - alt cont cu aceeași adresă (cel de pe web nu merge). wtf?",
                  "ONU: Lumea este pe cale să piardă lupta împotriva Ebola http://t.co/HSW3epEN0U",
                  "ONU: Lumea este pe cale să piardă lupta împotriva Ebola http://t.co/jzCNFd6OeY",
                  "http://t.co/hph763gd6O minecraft pe wiki 0 8 1",
                  "Am postat o fotografie nouă pe Facebook http://t.co/zrx3ERvwSR",
                  "Initiala baiatului/fetei pe care il/o placi http://t.co/pBPFTEGexr",
                  "Credinta zugraveste icoanele-n biserici dar si fotografiile de la Sf. Cuvioasa Parascheva http://t.co/EVjapppa0v",
                  "Am postat o fotografie nouă pe Facebook http://t.co/OWs9I2WWOQ",
                  "Frumusețea asta o înlocuiește pe Antonia! Epoca iubitei lui VELEA APUNE &gt;&gt; http://t.co/LHK97q4GT9 http://t.co/Kn3VcyTrKS",
                  "iauitațil pe Nicorescu Laurentiu când era mic, iauitați ce făcea! http://t.co/mqZHXEMgQP",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/jfJsQHOZto",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/KDFiLZ8y2g Gmod Sandbox Funny Moments – STUPID STAR WARS!",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/hJuBLI3s59",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/gcB8FYblb2",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/H10em8wzSn",
                  "El este groful grosier pe care Oreste il acuza ca a batjocorit padurile din Romania! http://t.co/YiX8EuAXWZ",
                  "Asta se întâmplă când lași crema de scutece pe mâna copiilor! :)) http://t.co/nLnuybf5Og",
                  "@joejonas esti un star,  iar starurile stralucesc.... Pe cand un nou hit?",
                  "#News Cine conduce SIE?: Avalanşa ofiţerilor acoperiţi de pe scena publică mă face să vă propun un exerciţiu… http://t.co/JNx5h0WKDl #Stiri",
                  "http://t.co/zLWVPQlrX8 minecraft pe wiki 0 8 1",
                  "#porno,#sex,#genç,#sicak,#kedi,#cinsel,#lezbiyen, | #Mature | Mature body pedagogical  http://t.co/SFCA3EpVZw",
                  "Să știți că eu rămân la ING, oricât ați luat voi să ne lăudați Libra aia. Dar, recunosc, bine țesută povestea, unii au crezut-o. Felicitări.",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/B0brSSSkj6 #stiri #romania #politica",
                  "Cele mai interesante reclame de pe Google http://t.co/carHjb1JQt",
                  "Cele mai interesante reclame de pe Google http://t.co/lFUog5JtGR",
                  "Cele mai interesante reclame de pe Google http://t.co/F3kw661xPn",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/V9slqwNbzH #stiri #romania #...",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/puc1ne6rnO #stiri #romania #politica",
                  "Am adăugat un videoclip la o listă de redare pe @YouTube, http://t.co/9c9arj0NF9 Feli - Cine te crezi? [Official video HD]",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/1iHjL06TMU #stiri #romania #politica",
                  "@chrisfelix92 @Ian3192 boqueton desde la peňa!!! Yiuuu",
                  "Am apreciat un videoclip pe @YouTube de la @soarrefuze, http://t.co/NhYUVVjT5n SoaR Refuze - Top 5 Trickshots Week #10",
                  "http://t.co/HtvF65GWwg minecraft pe wiki 0 8 1",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/ApCKTsuQXy",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/qJmwZIkwJA",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/bfCxU8j3yl",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/grWqvaoXIQ",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/sX6sWqZ9xr",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/Aa76jMZ8HX",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/UP9KtdULbg",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/NLC7CkvDuj",
                  "@aiurea intotdeauna, mai tare ca Tucescu, de fapt, eu l-am invatat pe Turcescu :)",
                  "Trei branduri ale Davino au pus umărul pentru o creştere de 30. ...: Trei branduri ale Davino au pus umarul pe... http://t.co/uQSRgV4aUY",
                  "Germania ar putea să ajute la resuscitarea economiei zonei euro dacă va simţi pe propria ...: Germania s ar pu... http://t.co/HjNmKnSC6g",
                  "A dat America pe Romania! S-a stabilit in Hunedoara si munceste pamantul cot la cot cu vecinii  http://t.co/ZeHK9KAlVj via @sharethis",
                  " lucruri pe care să NU le faci când copilul este nervos http://t.co/vAMqigxEqa #stiri",
                  "Michelle Obama face senzaţie pe internet: Prima Doamnă a Americii dansează cu o … legumă VIDEO http://t.co/LcoNgrGqfn #stiri",
                  "„Norocul îți bate la ușă”, dar și riști http://t.co/s8y7rlv5HU #stiri",
                  "STIRE: Licitaţia pentru hărţile de zgomot în porturi bate pasul pe loc - http://t.co/Fal7L7QUeb",
                  "DANIELA GYORFI - DU MA PE LUNA: http://t.co/AE9UifnKMb via @YouTube",
                  "Tipuri de SEX pe care oricine trebuie să le încerce într-o viaţă http://t.co/aWvgg79PLn #stiri",
                  "Virgil Diaconu despre ” blonda de la Cotroceni” : Şi acum tot 6,9 dar fără virgulă o să aibe în... http://t.co/hEQaRxOxNz",
                  "N-am să uit toamna în care,",
                  "",
                  ""]